### ISSUE TITLE
Unpin IPFS files for which there was no verification

### ISSUE THREAD

**Issue by shaharyakir** [ton-defi-org/ton-src-backend#6]
## Context
Currently, if the client supplies source code which compiles successfully to the given code cell hash:
1.  The json describing the sources and sources are uploaded to ipfs (example: https://tonsource.infura-ipfs.io/ipfs/QmNk7VA3zHfGQuT8nrSvPb8zvmpXbtE2BD51m55LXeaMWh)
2. signed boc to be sent to verifier registry is returned to the client

This is wasteful because if the user does not end up eventually sending the txn to the chain, we end up paying for a pinned file that is not in use.

## Suggestion: 
1. Maintain a database of sent ipfs handles per code cell hash
2. Run a background job (every 24hr or so) that, for each entry older than 30 minutes:
    * Checks whether the source item contract is deployed for the code cell hash
    * Otherwise we conclude the user has not issued the txn and we unpin the file from infura

## Possible risks:
1. We'd need to monitor health of the process
2. If the user has overridden the ipfs link (not likely since UI doesn't allow this), we will not clean it up
3. A mistake in the process may clean up files accidentally which is disastrous

## Alternative solutions
1. Pre-compute the ipfs hash without pinning (OR upload without pinning), then only pin after the client issues an API request which will be carried out after the deploy transaction is completed successfully on-chain.
    * This is risky (user may skip this step) and worsens UX (extra step)

**Comment by shaharyakir** [comment]
Decided on the solution to use hour-level verification timestamps in the json. this way multiple submissions made in an hour timeframe result in the same hash and therefore minimize littering the ipfs pinning node.

**Comment by Axsx22** [comment]
contract-verifier-container
contract-verifier-files
contract-verifier-file
contract-verifier-code
